version: '3.8'

services:
  client:
    build:
      context: ./Quickshow-client
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - quickshow-net

  server:
    build:
      context: ./Quickshow-Server
    ports:
      - "3000:3000"
    networks:
      - quickshow-net

networks:
  quickshow-net:
    driver: bridge
